name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          bash tools/setup_cloud.sh
          pip install build twine
      - name: Run tests
        run: |
          bash tools/run_tests.sh
      - name: Build wheel
        run: |
          python -m build
      - name: Publish wheel to Azure Artifacts
        if: github.event_name == 'push'
        env:
          TWINE_USERNAME: ${{ secrets.AZURE_ARTIFACTS_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PASSWORD }}
          FEED_URL: ${{ secrets.AZURE_ARTIFACTS_FEED_URL }}
        run: |
          python -m twine upload --repository-url "$FEED_URL" dist/*.whl
