name: Deploy Bicep

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev/test/prod)'
        required: true
        default: 'dev'
      location:
        description: 'Azure location'
        required: true
        default: 'eastus'
      baseName:
        description: 'Base name prefix'
        required: true
        default: 'leftturn'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        run: |
          az deployment sub create \
            --name leftturn-${{ github.run_id }} \
            --location "${{ github.event.inputs.location }}" \
            --template-file infra/bicep/main.bicep \
            --parameters env=${{ github.event.inputs.env }} location=${{ github.event.inputs.location }} baseName=${{ github.event.inputs.baseName }}
